name: Despliegue en GitHub

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: |
        npm install  

    - name: Construir la aplicación
      run: |
        npm run build  

    - name: Desplegar en GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        BRANCH: gh-pages  
        FOLDER: dist