name: Despliegue en GitHub

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: 
        npm install --force

    - name: Construir la aplicación
      working-directory: ./MySpotify
      run: 
        npm run build


    - name: Desplegar en GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        BRANCH: main
        FOLDER: MySpotify/dist/my-spotify